### ISSUE TITLE
BCBio project generation template

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#10]
At the moment, the AnalysisDriver runs:

```
bcbio_nextgen.py -w template gatk-variant ...
```

We should use a local template .yaml - gives us more control over what is run

**Comment by mwhamgenomics** [comment]
Also get BCBio to run alignment on all fastqs in the set - not just 2 per lane

**Comment by tcezard** [comment]
We also need to specify what the samples are in a csv file. This information should be extracted from the samplesheet for now but we could also get it from the LIMS eventually.
see http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#multiple-files-per-sample

**Comment by mwhamgenomics** [comment]
Opened #11 for parallelisation and .csv sample file
