### ISSUE TITLE
Datasets are not storing pid in the Reporting App

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#103]
Dataset are storing the pid when the process starts, however they don't seem to store them or retrieve them from the REST API.

**Comment by mwhamgenomics** [comment]
This was fixed [here](https://github.com/EdinburghGenomics/Analysis-Driver/commit/221d11740fd86fbf38b0ef69e3d4bdf719e36cd1#diff-78c92af3fe9b0232c7d1119d649d4d22) on 2/3/16
