### ISSUE TITLE
BCBio parallelisation

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#11]
At the moment, single BCBio jobs are passed to qsub. We should instead try to use BCBio's resource manager integration. We should also pass in a .csv of samples, so we can have a single BCBio process for the whole run.

**Comment by mwhamgenomics** [comment]
We should debug BCBio's `pbspro` workflow and consult the dev team about it. Problem seems to be allocation of PBS resources in the script header (resources requested exceed resources available)

**Comment by tcezard** [comment]
This will not get done at the moment
