### ISSUE TITLE
Compatibility with new cluster

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#128]
This will include:
- [x] Slurm ScriptWriter
- [ ] revisit #11 (BCBio supports Slurm)
- [x] config refs for data rsyncing
- [ ] data delivery
- [ ] LDAP for access to Lims, Rest API, etc.

**Comment by mwhamgenomics** [comment]
The new cluster currently has no way of viewing completed jobs (`squeue` only views currently running jobs, and running `sacct` results in 'SLURM accounting storage is disabled'. A few possible solutions:
- Periodically do an `squeue -j <job_id>` until it returns a non-zero exit status, indicating that the job is no longer running. This would break the pipeline as there would be no way of getting the exit status of a job.
- Use `salloc sh <script>` as an analog of `qsub -W block-true <script>`
- Enable accounting storage

**Comment by tcezard** [comment]
I think we should close this issue as all the work in Analysis driver is done
