### ISSUE TITLE
Data deletion tier 3

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#146]
We need to:
- check the Rest API for samples that have been reviewed and delivered
- check the Lims for samples where the most recent EG Data Release 1.0 is more than 3 months ago
- delete delivered_projects/project_id/release_date/sample_id

There will eventually be a user-notification step in the Lims. Once this is in, check that the sample has been through this.

**Comment by mwhamgenomics** [comment]
For now, just pass in a list of samples to delete from the `delivered` directory. From there, query the Rest API for project and proc ids, do the deletion and set the proc status to 'deleted'.

**Comment by tcezard** [comment]
I just noticed that there is a date in every LIMS process.
It only give the day but it should be enough for the purpose of knowing when the release happened.
Example:

``` python
l.get_processes(type='Data Release EG 1.0')[0].date_run
'2015-12-22'
```

**Comment by tcezard** [comment]
This has moved to EGCG-Project-Management
