### ISSUE TITLE
linking file in variant calling and qc pipeline is messy

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#149]
At the moment the variant calling pipeline uses the linking method to locate bcbio and some QC file and place them in the final directory. after the linking step some other QC steps are placing more file in the final directory using various mechanism.
The QC pipeline is different because the all file are generated before the linking method is called.

The two solutions are starting to diverge significantly and we should bring them back together.

**Comment by mwhamgenomics** [comment]
We should store output files in the `Dataset` object, building a list of expected output files, and search for them either after the stage finishes or at data output.

**Comment by mwhamgenomics** [comment]
This will be fixed as part of #59.

**Comment by tcezard** [comment]
This is now cleaner thanks to #59
