### ISSUE TITLE
add --kill or --stop option to analysis driver

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#193]
I'd like to have an option to stop a process from analysis driver.
analysis driver would identify the process from the REST API with its PID and send a signal SIGTERM (15) to the pid.
The running analysis driver would then catch that signal and cleanly exit:
- stop all executor jobs
- set its status to failed in the REST API.

**Comment by mwhamgenomics** [comment]
Opened [EGCG-Core#28](https://github.com/EdinburghGenomics/EGCG-Core/issues/28)

**Comment by tcezard** [comment]
This is now resolved
