### ISSUE TITLE
Test new bcl2fastq and support for new samplesheet format

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#20]
We need to test the new bcl2fastq to make sure that the output directory structure is still the same.
We also need to change our samplesheet parser to support the new headers.

**Comment by mwhamgenomics** [comment]
For sample sheet header task, see [Asana #43189233113006](https://app.asana.com/0/42565309760409/43189233113006) 'AnalysisDriver is crashing in production'
