### ISSUE TITLE
Support for multiple version of tools

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#222]
We want to be able to update our tools while still guaranteeing that samples from a project will be run with a specific stable set of tools.
We need to be able to associate a set of tools (config file) and a workflow (analysis_driver version) with a project. The config file and analysis_driver version will be retrieved before analysis driver starts.

One option would be to split Analysis-Driver in two: 
 - Process manager on one side
 - Pipeline runner on the other

Another option would be to add a wrapper script around AnalysisDriver to select the version to run.

**Comment by mwhamgenomics** [comment]
Current structure:

- tool_versioning.yaml contains toolsets with tool versions
  - e.g, toolset 1 has bwa 1.2.4
- toolset object contains paths and metadata for all third party executables
  - toolset.select_toolset(1)
  - toolset['bwa'] -> `path/to/bwa`
  - references to `cfg['tools']['bwa']` should now be toolset['bwa']
- This means the toolset can be selected at runtime, so no need for a separate wrapper script
- We can then develop updated pipelines and freeze them with toolset versions
- We need to store what pipeline has been run on a project, defaulting to the newest pipeline
  - This is fine for samples and projects, but what about runs?
