### ISSUE TITLE
Sample sheet parsing

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#228]
In Seqlab 2, some of the sample sheet columns have changed:

- Sample_ID and Sample_Name have swapped roles
- Index and Index2 are no longer capitalised
- Project_Name no longer needs to be converted to Sample_Project

Some of the fuzzy logic for locating columns can probably be removed as well, since our sample sheet format is fairly stable now.

**Comment by tcezard** [comment]
Sorry for reopening but it turns out the pooling run samplesheet has another problem.
The Samplesheet contains both barcodes values (index and index2) and bcl2fastq only expects one.
We need to remove the index2 regardless of the run
