### ISSUE TITLE
test and integrate bcl2fastq2.20

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#231]
Download bcl2fast 2.19 from
https://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software.html
The basic behaviour seems but the stats seems to have changed. That might require some change in the parsers

**Comment by tcezard** [comment]
bcl2fastq v2.17 has a bug where the ConservationStats.xml does not report the accurate number of base in the yield. (see validation report for detail)
Check that new version has this fixed.

**Comment by tcezard** [comment]
bcl2fastq 2.20 is available and we should test this one instead of bcl2fastqv2.19 
http://emea.support.illumina.com/downloads/bcl2fastq-conversion-software-v2-20.html

**Comment by tcezard** [comment]
bcl2fastq stage 
https://github.com/EdinburghGenomics/Analysis-Driver/blob/0c78342d84ab158fc22da88dfe5505353d79c6f1/analysis_driver/pipelines/demultiplexing.py#L71

bcl2fastq command
https://github.com/EdinburghGenomics/Analysis-Driver/blob/0c78342d84ab158fc22da88dfe5505353d79c6f1/analysis_driver/util/bash_commands.py#L11

**Comment by lukbut** [comment]
This issue will be resolved with this PR https://github.com/EdinburghGenomics/Analysis-Driver/pull/369
