### ISSUE TITLE
Recording data processed in the analysis driver proc

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#260]
https://github.com/EdinburghGenomics/Reporting-App/pull/109 introduced the possibility of adding a source of the data to analysis driver proc. We should store there:
 - The list of run element id for sample process
 - The list of sample id for Project process

**Comment by katieemelianova** [comment]
Make sure that --resume option uses the same run_elements - safeguard against pause/change reviewed run elements/resume/use different set of run elements on resume to the ones recorded in proc
