### ISSUE TITLE
ClusterExecutor.run logging blocks until PBS job completed

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#29]
At line 48, self.proc.stdout.readline() hangs, meaning that the job ID is not logged until it's completed

**Comment by mwhamgenomics** [comment]
Apparently this is something to do with qsub not flushing its output soon enough. Not really much that can be done about it in that case.

**Comment by tcezard** [comment]
I think we could get that to work if we change the way executors works. We would run the qsub jobs without block and monitor the job with qstat after that.

**Comment by tcezard** [comment]
This won't be an issue anymore in the new cluster
