### ISSUE TITLE
Extend QC to calculate variant calling for non human

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#305]
This would allow us to calculate new metrics:
 - ti/tv ratio
 - het/hom ratio
and upload them to the reporting app.

**Comment by tcezard** [comment]
Mimic what is being done in BCbio to generate the vcf and filtering then run vcfstat

**Comment by tcezard** [comment]
Associated with CR630

**Comment by katieemelianova** [comment]
Integration tests passing
