### ISSUE TITLE
Handle error in asana notification

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#327]
There has been few instances of ConnectionTimeout on Asana API which could be caused by their server being too slow or our query taking too long.
In any case, when it occurs during a failure the asana task is created and because the resulting exception is not handled the status of the pipeline is not changed.
We need to make sure our queries are not taking too long and handle error in notification so that if one fails the other one can still be notified.

**Comment by tcezard** [comment]
It looks like the issue we experience was actually due to an outage on Asana
https://trust.asana.com/incidents/dfgh69vv5qk3
https://trust.asana.com/incidents/10bl90c8pcyr
Not due to the load of the query.
We should still look at protecting the other notification from one failing.

**Comment by mwhamgenomics** [comment]
Should this be done here or in EGCG-Core?

**Comment by tcezard** [comment]
Thats a fair point I'll close it here and open it in EGCG-Core in https://github.com/EdinburghGenomics/EGCG-Core/issues/79
