### ISSUE TITLE
Run crawler crashes if the insert size metric is missing

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#352]
If the insert size in orientation FR is missing the RunCrawler will crash with KeyError.
https://github.com/EdinburghGenomics/Analysis-Driver/blob/b635c498126bf374f2774438db3c1ea04663176b/analysis_driver/report_generation/run_crawler.py#L342
Adding an if allows it to upload the information available.

**Comment by mwhamgenomics** [comment]
The following changes were made in production to analysis_driver/report_generation/run_crawler.py:

```git
-                mapping_statistics.update(insert_types.pop('FR'))
+                if 'FR' in insert_types: 
+                    mapping_statistics.update(insert_types.pop('FR'))
```
