### ISSUE TITLE
Fastq file passed to bcbio are not the merged ones

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#36]
But they're the input of the merge
I think bcbio_prepare_samples should return the merged files it generates so they can be passed to bcbio
https://github.com/EdinburghGenomics/Analysis-Driver/blob/master/analysis_driver/driver.py#L149

**Comment by mwhamgenomics** [comment]
Should just be a case of adding `'-merged'` into the file name returned. Will wait for merge #37, as the file involved has changed a bit.

**Comment by tcezard** [comment]
V0.61 still does not run bcbio with the merged fastq file
I think it the creation of the Yaml file using bcbio template that is wrong here.
Can we test that it work before putting in production?

**Comment by tcezard** [comment]
I think https://github.com/EdinburghGenomics/Analysis-Driver/commit/8f289667ee2066a6983a0109d4abd0588cfa0d02 fixes this
