### ISSUE TITLE
Ensure all files have been transferred before starting run processing

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#363]
In some cases, some bcl files were missing at the beginning of the Run processing due to the transfer lagging behind. 
We should check that all the file are present and if they're not add another 5 mins wait.

Related to issues documented in NC163.

**Comment by mwhamgenomics** [comment]
Wasn't there also a problem with files being present but incomplete?

**Comment by tcezard** [comment]
The current process does not differentiate between missing and incomplete file so in short, I don't know.
We should obviously check for both presence and completeness.

**Comment by lukbut** [comment]
@tcezard @mwhamgenomics Do you happen to have an Asana issue related to this issue please, so I can pinpoint where the process is failing?

**Comment by lukbut** [comment]
Following a discussion with @tcezard today, the function that needs to be changed was confirmed as "check_bcls" in analysis_driver/quality_control/bcl_validation.py.

**Comment by lukbut** [comment]
One possible approach would be to calculate the number of BCLs expected for a run, and then to check the number of BCLs on the file system to confirm whether this matches. This check would be in a while loop and succeeded by a 5 minute sleep, which would allow any file transfers which are in progress to complete. An upper waiting time limit should be set, to prevent the while loop from continuing forever.
