### ISSUE TITLE
Spam reduction

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#365]
At the moment, the messages that the pipeline logs are very verbose. We should review the logging and notifications, remove stuff we don't use and potentially add things we want to see.

**Comment by tcezard** [comment]
Can you list the things you'd like to see remove/added?

**Comment by mwhamgenomics** [comment]
Suggested logging changes:

- Remove version_cmd Toolset debug messages, replace with `resolved tool {tool} version {version}' info message
- Bump BCBio 'Using merged fastqs: ...' message from `debug` to `info`
- Ensure that all bash commands run are logged to `info`, remove duplicate messages, e.g. bcl2fastq

Having `--debug` as an option is also not ideal for an automated process. Can do what BCBio does and write both a normal and a debug log, perhaps?

**Comment by lukbut** [comment]
@mwhamgenomics How large is the debug log? Would the additional storage space needed from always logging debug logs be of concern?

**Comment by mwhamgenomics** [comment]
Given the changes introduced in #375, the debug log will be no bigger than the log we currently write with `--debug` enabled. It will only be written to the job folder, so will be cleaned up after the pipeline finishes.
