### ISSUE TITLE
Species/Genomes in the reporting app 

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#367]
- [x] Migrate from using a list of species/genomes from the config to using the ones stored in the reporting app. 
 - [x] Store the genome used during sample processing in analysis_driver_procs
 - [x] Enforce the the project whitelist, i.e. only process a sample if the project ID is in the whitelist, or the whitelist is missing.
 - [x] Remove support for "known_indels" in the genome reference data

Validation ID: VB8

**Comment by mwhamgenomics** [comment]
We should also respect the project whitelist, i.e. only process a sample if the project ID is in the whitelist, or the whitelist is empty.

**Comment by tcezard** [comment]
Thanks I've edited the description

**Comment by lukbut** [comment]
Work on this issue is paused pending feedback on where to implement the whitelisting functionality by @tcezard

**Comment by lukbut** [comment]
Today, @tcezard suggested adding the whitelisting functionality to analysis_driver/dataset.py - reference_genome(). The functionality will raise an analysis_driver error which will handle the halting of any processes and consequent notification.

**Comment by lukbut** [comment]
Integration test integration_test_9ad4dB ran successfully on this branch.
