### ISSUE TITLE
record version of tools used

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#376]
At the moment we record the version of all the tools available is written to a yaml file at the end of the pipeline. As more tools gets added to the configuration file the number of tools in the yaml file will grow even if they are not used in the pipeline that ran.
We should record in the toolset the tool used in a particular run and only output these tool versions to the yaml files

**Comment by mwhamgenomics** [comment]
This is complicated. At the moment if we resume and haven't yet written the file, anything from stages already run will not be present. Also storing tools in the object is not process-safe. We thought of three solutions:

1) this would involve making toolset belong to the dataset and finding a way of referencing toolset in util.bash_commands
2) or we could keep toolset global and update `self.version_file` upon dataset initialisation, e.g. alongside toolset.select_type/select_version
3) Manually enforcing that tool versioning.yaml is up to date. We can't guarantee that this will be reliable

Will try solution 2 for now.
