### ISSUE TITLE
Rsync efficiency

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#51]
At the moment, if an intermediate_dir is specified, all dataset is automatically synced from the RDF to the intermediate. There's a fair amount of data that's not needed by the run, e.g Logs, Thumbnail_Images, etc. so if we exclude these from the rsync, we would free up some space in /scratch and also reduce the delay before the pipeline starts.

**Comment by mwhamgenomics** [comment]
According to Illumina's [bcl2fastq guide](http://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v2-17-software-guide-15051736-g.pdf), it needs the following:
- binary files
  - bcl.gz
  - filter
  - s.locs
- RunInfo.xml
- SampleSheet.csv

**Comment by tcezard** [comment]
I check the size of the directory:
92K     analysis_driver.log
216K    Config
637G    Data
0  fastq
252M    InterOp
1.7G    Logs
4.0K    PeriodicSaveRates
24K     Recipe
4.0K    RTAComplete.txt
8.0K    RTAConfiguration.xml
278M    RTALogs
4.0K    RTARead1Complete.txt
4.0K    RTARead2Complete.txt
4.0K    RTARead3Complete.txt
28K     RunInfo.xml
12K     runParameters.xml
4.0K    SampleSheet_analysis_driver.csv
4.0K    SampleSheet.csv
4.0K    SequencingComplete.txt
48G     Thumbnail_Images
The only one that seems worth skipping are the thumbnail images  but that would only save 5-10%
