### ISSUE TITLE
Executor overhaul

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#55]
The usage of the Executor classes is a bit complex at the moment. An ideal situation would be:
- build up a list of Bash commands
- call, e.g, executor.execute(bash_commands, cluster=True, block=False)
- if cluster == True, then use PBSWriter/ClusterExecutor
  - if len(bash_commands) > 1, then write a  job array

We should also consolidate the Threaded exception-catching from quality_control.GenotypeValidation

**Comment by tcezard** [comment]
You should allow arbitrary parameters to be passed with kwargs in the executor.
I don't you need every jobs to specify if they should be run on the cluster or locally but the executor should make that decision based on the config file.
A mechanism for bypassing this might be useful ie: force_ job_execution = 'local'
