### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#56]
We should have some tests that can be run on the cluster to test BCBio, PBS, etc. A couple of test datasets would be good too.

**Comment by tcezard** [comment]
To get integration test in place means we need data/binaries/configs/run environment. This is all feasible but the first step is to get our unit test run automatically.
I've create a travis CI yaml file which should run pytest on the master.

**Comment by tcezard** [comment]
Would https://github.com/lastbackend/lastbackend be useful for managing the test images

**Comment by tcezard** [comment]
This is now done
