### ISSUE TITLE
Output file discovery

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#58]
At the moment, the pipeline iterates through sample IDs and expects to find specific files in specific places. This enforces consistency, but breaks easily if a file name configuration is wrong, and the code for it is not very clear.
1. We should use `glob.glob` to be more lenient with file names (e.g, `-ready-bam.bai` vs `-ready.bam.bai`)
2. We should discover/transfer all files that are there, then check that we have everything we expected.
3. At the moment, the driver returns a non-zero exit status if there are missing output files. Should this be the case (since the transfer of files was technically successful)?

**Comment by tcezard** [comment]
1. Being rigid for file naming is good unless we're planning to support multiple file name in which case we should explicitly allow for multiple file names by enumerating them all
2. I guess your point is that we should not break half way through the transfer in case one file is missing. I would argue that if any expected file is missing then something went wrong so this step should be redone anyway. We could separate the file discovery from the transfer and transfer no file at all if any one is missing.
3. Yes I think that is what we want.

**Comment by tcezard** [comment]
They're more file we will need to either keep or parse to extract the information and output.
The file I can think of for now are:
- bamtools stat output:
  path --> bcbio_dir,'final', lib_name, 'qc','bamtools', 'bamtools_stats.txt'
  ( [link](https://github.com/EdinburghGenomics/report_generation/blob/master/bcbio_report.py#L29), [Parser](https://github.com/EdinburghGenomics/report_generation/blob/master/report_generation/readers/mapping_stats_parsers.py#L8))
- bcbio metric file in yaml:
  path -->  bcbio_dir,'work', 'align', lib_name,'%s-sort-highdepth-stats.yaml'%lib_name
  ( [link](https://github.com/EdinburghGenomics/report_generation/blob/master/bcbio_report.py#L40),  [Parser](https://github.com/EdinburghGenomics/report_generation/blob/master/report_generation/readers/mapping_stats_parsers.py#L39))
- bcbio callable bed file in yaml:
  path -->  bcbio_dir,'work', 'align', lib_name,'%s-sort-callable.bed'%lib_name
  ( [link](https://github.com/EdinburghGenomics/report_generation/blob/master/bcbio_report.py#L44),  [Parser](https://github.com/EdinburghGenomics/report_generation/blob/master/report_generation/readers/mapping_stats_parsers.py#L28))
- demultiplexing conversion stat in xml:
  path -->  run_dir,/fastq/Stats/ConversionStats.xml
  ([Parser](https://github.com/EdinburghGenomics/report_generation/blob/master/report_generation/readers/demultiplexing_parsers.py#L23))

There are probably other file as well

**Comment by tcezard** [comment]
We should also record the config file (with a dump from the config object) and the log file.
It might not make sense to copy the log and config to every sample output. 
We might need to create a run output in the processed folder to store this kind of information.
