### ISSUE TITLE
Stage modularity

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#59]
At the moment, the pipeline runs end-to-end, regardless of whether it has already done some stages. We should explicitly split up the pipeline into stages, allowing it to track/reset progress. This way we won't, e.g, need to rerun the rsync or bcl2fastq if we only need to run BCBio.

**Comment by mwhamgenomics** [comment]
Suggested additions:
- Dataset object contains info to be shared across stages
  - [ ] expected output files
  - [ ] cumulative exit status (unless we want to stop the pipeline on any uncaught exception)
  - [ ] tool versions
  - [ ] which Luigi end stage to call
- `luigi.Target` subclasses for Stage outputs
  - [x] A RestAPITarget that checks `self.dataset` for Rest API stages
  - [ ] A FileTarget that checks for existence of registered output files
- Stage contains universal boilerplate
  - [x] RestAPITarget (instead of stage lock file)
  - [x] notifications
  - [ ] if it uses a tool, records it in the Dataset
  - [ ] specify output files to be registered to the Dataset
- DataOutput stages for runs and samples
  - [ ] Run appropriate QCCrawlers
  - [ ] Do MD5s for all registered output files

**Comment by mwhamgenomics** [comment]
This is naturally a large change to the project. Instead of converting all of `pipelines` to Luigi Tasks, we discussed just setting up the Luigi infrastructure and having simple one-stage pipelines that just run the functions already there in `pipelines`. We would then work on segmenting them later.

This would mean that the stages seen in the reporting app will change. We don't have anything that looks for specific stages, do we? (e.g. in EGCG-Project-Management)

**Comment by mwhamgenomics** [comment]
Now that #216 is merged, we can start on segmenting the pipeline.

**Comment by tcezard** [comment]
This is now done
