### ISSUE TITLE
Automatic cleanup

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Analysis-Driver#60]
If all processing stages run successfully, we should have the pipeline remove the intermediate files (fastqs, vcfs, bams, etc.). Otherwise, it should notify that some manual cleanup/re-running will be needed. This will be dependent on #58 and #59.

**Comment by mwhamgenomics** [comment]
For now, check for zero-exit status and remove the `jobs` and `input_data` folders if everything went fine. Also comment out `genotype_validation`.

**Comment by tcezard** [comment]
I think this is now done

**Comment by mwhamgenomics** [comment]
We should have a decoupled process that scans the jobs directory, checks whether the run/sample is done, and then cleans it up.

**Comment by tcezard** [comment]
We can now do the data cleanup properly within the new cluster
