### ISSUE TITLE
Failed runs can be detected as valid

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#68]
When sequencing runs are failed the RTAcomplete.txt might be added to the run folder and processed as if it was successful.
Before processing the run we should query the LIMS to make sure the run is successfully finished

**Comment by tcezard** [comment]
The check on the LIMS will not prevent the run from being processed.
We can let the run processing fail (exit status != 0) and mark  the run as unusable on the reporting app.

**Comment by mwhamgenomics** [comment]
The driver raises an `AnalysisDriverError` if the run status is not 'RunCompleted'. Instead, we should automatically mark the run as aborted.
