### ISSUE TITLE
get the length of the barcode from the samplesheet instead of the runparameters.xml

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#7]
the barcode length seems to be hardcoded in the machine recipe which mean we can't change it.
to ensure that the demultiplexing happens properly we need to retrieve the barcode length from the samplesheet instead of the runparameters.xml

**Comment by mwhamgenomics** [comment]
We should still get the barcode length from RunInfo.xml, but add a validation check that this is consistent with SampleSheet.csv. If they don't, raise an error/stop the program.

**Comment by mwhamgenomics** [comment]
Implemented OO sample sheet and run info parsing, and added a check to ensure they agree. See commit 396ec1c (Jul 14)
