### ISSUE TITLE
Quality control: Contamination check

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#73]
We should run verify bam ID without prior to get an estimate of the purity of the sample

**Comment by mwhamgenomics** [comment]
Run verifyBAMID, transfer `sample_id_best.selfSM` to output_dir, parse and send to the reporting DB

**Comment by tcezard** [comment]
I just moved that issue to 0.9.3 as it might take us a bit more time to finish it

**Comment by katieemelianova** [comment]
3 papers discussing within species contamination:
Occult Specimen Contamination in Routine Clinical Next-Generation Sequencing Testing.

Detecting and estimating contamination of human DNA samples in sequencing and array based genotype data

ContEst: Estimating cross-contamination of human samples in next-generation sequencing data
