### ISSUE TITLE
Add force option to to force start a process that is not ready

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#74]
The sample processing require that the dataset has enough data to be processed.
We need an options to force start the analysis to bypass this requirement.

**Comment by mwhamgenomics** [comment]
Would we want to be able to force-start both samples and runs? If so, we can add a `force` method to the `Dataset` superclass and if not, just to `SampleDataset`.

**Comment by tcezard** [comment]
I think having it for SampleDataset only makes sense for now. There might be few cases where we would want to run a RunDataset before the RTAComplete.txt appear but it not really something we plan to do
