### ISSUE TITLE
Rsync command do not update all files

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Analysis-Driver#89]
Had a strange situation where rsync of a sample folder to the/PROCESSED folder did not update a file.
I'm blaming the --size-only option in our rsync command at the moment but don't have hard evidence.
We need to make sure the rsync update all files when necessary by checking also timestamp.

**Comment by mwhamgenomics** [comment]
We should also get rsync to preserve file permissions (if that's not possible, hard-set them to be group-writable and others-inaccessible)

**Comment by mwhamgenomics** [comment]
It looks like `--size-only` and `--append-verify` both cause rsync to skip files that are the same size. We'd have to either remove these arguments from `bash_commands.rsync_from_to`, or make them optional.
